### PR TITLE
SharePoint2010SearchProgrammatically.html

### PR DESCRIPTION
**Pull request by svadwlas**
Search inside SharePoint 2010 programmatically using a JavaScript library "SPServices".

### CODE REVIEW

**Comment by Rick-Kirkham** [comment]
@svadwlas 
Please provide an explanation for why you want to add this file. Also, how will users of the sample navigate to this file?

**Comment by svadwlas** [comment]
Rick,

I wanted to add an reference with regards to searching SharePoint 2010 programmatically on the lines of SharePoint 2013 (using the keyword query language (KQL) syntax as an input)- since 2010 is still the most widely prevalent legacy platform version out there. 

"Also, how will users of the sample navigate to this file?" - I am not sure if I got the context in which this question was asked.  I can set it up in the form of another ".aspx" page by adding it to the current Visual Studio solution you have, or create another project folder specifically targeting the 2010 version. Please let me know.  I can include the SPServices script as well.

**Comment by Rick-Kirkham** [comment]
@svadwlas 
Your file should be in an entirely separate sample in its own repo. This sample is specifically intended to demonstrate searching with the REST APIs.

**Comment by svadwlas** [comment]
Sure. Thanks Rick for your time.

**Pull request closed without merging**
